### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './dataset/ILSVRC/downsampled_lmdb/imagenet16/train_data_batch_1'

### ISSUE THREAD

**Issue by Hangyul-Son** [epfml/federated-learning-public-code#10]
Hello! I hope you are having a wonderful day. 

I could simulate FedAvg and Fedprox thanks to your code. However when I tried to simulate FedDF with distillation dataset Imagenet16/32/64, below error occurs. If I simulate using cifar100/cifar10 for the distillation dataset the problem doesn't exist and would safely complete the simulation. 

```
2023-01-09 15:33:19	Data partition for train (client_id=1): partitioned data and use subdata.
2023-01-09 15:33:19		Data stat for train: # of samples=2250 for client_id=1. # of batches=36. The batch size=64
2023-01-09 15:33:19	Master initialized the local training data with workers.
2023-01-09 15:33:19	Data partition for validation/test.
2023-01-09 15:33:19		Data stat for validation/test: # of samples=5000 for Master. # of batches=79. The batch size=64
2023-01-09 15:33:19	Master initialized val data.
2023-01-09 15:33:19	Data partition for validation/test.
2023-01-09 15:33:19		Data stat for validation/test: # of samples=10000 for Master. # of batches=157. The batch size=64
2023-01-09 15:33:19	Master initialized model/dataset/criterion/metrics.
2023-01-09 15:33:19	create data=imagenet16 for aggregation.
Traceback (most recent call last):
  File "main.py", line 90, in <module>
    main(conf)
  File "main.py", line 28, in main
    process = Master(conf) if conf.graph.rank == 0 else Worker(conf)
  File "/py/codes/FedDF-code/pcode/master.py", line 109, in __init__
    self.aggregator = create_aggregator.Aggregator(
  File "/py/codes/FedDF-code/pcode/create_aggregator.py", line 29, in __init__
    self.data_info = self._define_aggregation_data(return_loader=True)
  File "/py/codes/FedDF-code/pcode/create_aggregator.py", line 173, in _define_aggregation_data
    dataset = prepare_data.get_dataset(
  File "/py/codes/FedDF-code/pcode/datasets/prepare_data.py", line 334, in get_dataset
    return _get_imagenet(conf, name, datasets_path, split)
  File "/py/codes/FedDF-code/pcode/datasets/prepare_data.py", line 266, in _get_imagenet
    return imagenet_folder.ImageNetDS(
  File "/py/codes/FedDF-code/pcode/datasets/loader/imagenet_folder.py", line 82, in __init__
    with open(file, "rb") as fo:
FileNotFoundError: [Errno 2] No such file or directory: './dataset/ILSVRC/downsampled_lmdb/imagenet16/train_data_batch_1'
```

May you give me advice on where the problem might be? 

Thank you in advance!!

**Comment by tlin-taolin** [comment]
you should download the corresponding datasets from the links provided in this [repo](https://github.com/PatrykChrabaszcz/Imagenet32_Scripts).
