### ISSUE TITLE
Environments pytorch-mpi Error

### ISSUE THREAD

**Issue by YangWenhao3906** [epfml/federated-learning-public-code#4]
Hello, can you help me?

When I ran the dockerfile, I got this problem. I tried two times but got the same result. 

```
Service 'pytorch-mpi' failed to build: The command '/bin/sh -c cd pytorch &&     git checkout v1.6.0 &&     git submodule sync &&     git submodule update --init &&     TORCH_CUDA_ARCH_LIST="3.5 3.7 5.2 6.0 6.1 7.0+PTX" TORCH_NVCC_FLAGS="-Xfatbin -compress-all"     CMAKE_PREFIX_PATH="$(dirname $(which $HOME/conda/bin/conda))/../"     pip install -v .' returned a non-zero code: 1
```

I paste the shell output below.

```
Compiling  reduce_scatter.cu                   > /tmp/pip-req-build-ohe1j5l4/build/nccl/obj/collectives/device/reduce_scatter_max_f32.o
Compiling  reduce_scatter.cu                   > /tmp/pip-req-build-ohe1j5l4/build/nccl/obj/collectives/device/reduce_scatter_max_f64.o
Compiling  functions.cu                        > /tmp/pip-req-build-ohe1j5l4/build/nccl/obj/collectives/device/functions.o
Archiving  objects                             > /tmp/pip-req-build-ohe1j5l4/build/nccl/obj/collectives/device/colldevice.a
Linking    libnccl.so.2.4.8                    > /tmp/pip-req-build-ohe1j5l4/build/nccl/lib/libnccl.so.2.4.8
Generating nccl.pc.in                          > /tmp/pip-req-build-ohe1j5l4/build/nccl/lib/pkgconfig/nccl.pc
Archiving  libnccl_static.a                    > /tmp/pip-req-build-ohe1j5l4/build/nccl/lib/libnccl_static.a
/tmp/pip-req-build-ohe1j5l4/third_party/nccl/nccl/src
[ 47%] No install step for 'nccl_external'
[ 47%] Completed 'nccl_external'
[ 47%] Built target nccl_external
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ohe1j5l4/setup.py", line 732, in <module>
        build_deps()
      File "/tmp/pip-req-build-ohe1j5l4/setup.py", line 316, in build_deps
        cmake=cmake)
      File "/tmp/pip-req-build-ohe1j5l4/tools/build_pytorch_libs.py", line 62, in build_caffe2
        cmake.build(my_env)
      File "/tmp/pip-req-build-ohe1j5l4/tools/setup_helpers/cmake.py", line 345, in build
        self.run(build_args, my_env)
      File "/tmp/pip-req-build-ohe1j5l4/tools/setup_helpers/cmake.py", line 141, in run
        check_call(command, cwd=self.build_dir, env=env)
      File "/home/user/conda/envs/pytorch-py3.6/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 2.
    Running setup.py install for torch: finished with status 'error'
ERROR: Command errored out with exit status 1: /home/user/conda/envs/pytorch-py3.6/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ohe1j5l4/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ohe1j5l4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jqt6xg4j/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/conda/envs/pytorch-py3.6/include/python3.6m/torch Check the logs for full command output.
ERROR: Service 'pytorch-mpi' failed to build: The command '/bin/sh -c cd pytorch &&     git checkout v1.6.0 &&     git submodule sync &&     git submodule update --init &&     TORCH_CUDA_ARCH_LIST="3.5 3.7 5.2 6.0 6.1 7.0+PTX" TORCH_NVCC_FLAGS="-Xfatbin -compress-all"     CMAKE_PREFIX_PATH="$(dirname $(which $HOME/conda/bin/conda))/../"     pip install -v .' returned a non-zero code: 1
```

**Comment by aqibsaeed** [comment]
Facing the same issue, I tried several times but no luck. Any ideas how to solve this issue?

**Comment by tlin-taolin** [comment]
updated a new env (not fully tested), please re-open the ticket if the issue still exists.

**Comment by aqibsaeed** [comment]
Seems like it builds successfully. Do I also need to start docker container and activate a particular conda environment? Could you please list commands?

**Comment by its-Ahmad** [comment]
I am having the same problem... Any solutions please?
