### ISSUE TITLE
FileNotFoundError: [Errno 2]

### ISSUE THREAD

**Issue by Hangyul-Son** [epfml/federated-learning-public-code#9]
Hello. I am very sorry to bother you again. 

After all dependencies and compatibility issues have been resolved, when I run the command provided by the repository, 

````
python run.py \
    --arch resnet8 --complex_arch master=resnet8,worker=resnet8 --experiment demo \
    --data cifar100 --pin_memory True --batch_size 64 --num_workers 2 \
    --partition_data non_iid_dirichlet --non_iid_alpha 1 --train_data_ratio 1 --val_data_ratio 0.1 \
    --n_clients 20 --participation_ratio 0.1 --n_comm_rounds 100 --local_n_epochs 40 --world_conf 0,0,1,1,100 --on_cuda True \
    --fl_aggregate scheme=noise_knowledge_transfer,update_student_scheme=avg_logits,data_source=other,data_type=train,data_scheme=random_sampling,data_percentage=1.0,data_name=imagenet32,data_dir=./dataset/ILSVRC,total_n_server_pseudo_batches=10000,eval_batches_freq=100,early_stopping_server_batches=1000 \
    --img_resolution 32 \
    --optimizer sgd --lr 0.1 --local_prox_term 0 --lr_warmup False --lr_warmup_epochs 5 --lr_warmup_epochs_upper_bound 150 \
    --lr_scheduler MultiStepLR --lr_decay 0.1 \
    --weight_decay 0 --use_nesterov False --momentum_factor 0 \
    --track_time True --display_tracked_time True --python_path $HOME/conda/envs/pytorch-py3.8.12/bin/python --hostfile hostfile \
    --manual_seed 7 --pn_normalize False --same_seed_process False
````

I am facing the below file not found error. It seems like the logger cannot create the file,, but I am unclear what the exact issue may be. May you possibly know what the potential issue might be?

`2023-01-06` 08:39:22		=> Master created model 'resnet8. Total params: 0.083892M
Traceback (most recent call last):
  File "main.py", line 90, in <module>
    main(conf)
  File "main.py", line 28, in main
    process = Master(conf) if conf.graph.rank == 0 else Worker(conf)
  File "/py/codes/FedDF-code/pcode/master.py", line 30, in __init__
    _, self.master_model = create_model.define_model(
  File "/py/codes/FedDF-code/pcode/create_model.py", line 25, in define_model
    get_model_stat(conf, model, arch)
  File "/py/codes/FedDF-code/pcode/create_model.py", line 89, in get_model_stat
    conf.logger.log(
  File "/py/codes/FedDF-code/pcode/utils/logging.py", line 42, in log
    self.save_txt(content)
  File "/py/codes/FedDF-code/pcode/utils/logging.py", line 57, in save_txt
    write_txt(value + "\n", self.file_txt, type="a")
  File "/py/codes/FedDF-code/pcode/utils/op_files.py", line 33, in write_txt
    with open(out_path, type) as f:
FileNotFoundError: [Errno 2] No such file or directory: ./data/checkpoint/cifar100/resnet8/demo/1672965561_l2-0.0_lr-0.1_n_comm_rounds-100_local_n_epochs-40.0_batchsize-64_n_clients_20_n_participated-2_optim-sgd_agg_scheme-noise_knowledge_transfer/0/log.txt`

Thank you very much for the support. Have a great day!

**Comment by Hangyul-Son** [comment]
Actually the problem occured because of the docker container did not have permission to create directories. 

Now it is working fine! Please run the command, 

`docker run --rm -it --user root --gpus all -v $PWD:/py -w /py user/pytorch-mpi`

with root permission (--user root) to create directories inside docker images and with all the gpus (--gpus all) so to avoid cuda.is_available() -> false error.

After that inside the interactive mode,
`export OMPI_ALLOW_RUN_AS_ROOT=1`
`export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1`

Then run the command based on the ### **python version**

`python run.py \
--arch resnet8 --complex_arch master=resnet8,worker=resnet8 --experiment demo \
--data cifar10 --pin_memory True --batch_size 64 --num_workers 2 \
--partition_data non_iid_dirichlet --non_iid_alpha 1 --train_data_ratio 1 --val_data_ratio 0.1 \
--n_clients 20 --participation_ratio 0.1 --n_comm_rounds 100 --local_n_epochs 40 --world_conf 0,0,1,1,100 --on_cuda True \
--fl_aggregate scheme=federated_average \
--optimizer sgd --lr 0.1 --local_prox_term 0 --lr_warmup False --lr_warmup_epochs 5 --lr_warmup_epochs_upper_bound 150 \
--lr_scheduler MultiStepLR --lr_decay 0.1 \
--weight_decay 0 --use_nesterov False --momentum_factor 0 \
--track_time True --display_tracked_time True --python_path $HOME/conda/envs/pytorch-py3.8.12/bin/python3 --hostfile hostfile \
--manual_seed 7 --pn_normalize True --same_seed_process False`

Thank you :)
